// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2JKZkFCgxuJFd8GgPphPd2s83FIt9zgw',
    appId: '1:74657022222:web:8fd0cfe93c67580c8cd75f',
    messagingSenderId: '74657022222',
    projectId: 'lab-firebase-bb91b',
    authDomain: 'lab-firebase-bb91b.firebaseapp.com',
    storageBucket: 'lab-firebase-bb91b.firebasestorage.app',
    measurementId: 'G-17KTPDPYNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCIxs8D0gGI9Gx1fPWVs8Nn8j9-dPoHVE',
    appId: '1:74657022222:android:f960088771f740da8cd75f',
    messagingSenderId: '74657022222',
    projectId: 'lab-firebase-bb91b',
    storageBucket: 'lab-firebase-bb91b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQzklttLPFMOMeazt1YydfdSDgSndMOI',
    appId: '1:74657022222:ios:f31b9586a6d4bf828cd75f',
    messagingSenderId: '74657022222',
    projectId: 'lab-firebase-bb91b',
    storageBucket: 'lab-firebase-bb91b.firebasestorage.app',
    iosBundleId: 'com.example.labFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMQzklttLPFMOMeazt1YydfdSDgSndMOI',
    appId: '1:74657022222:ios:f31b9586a6d4bf828cd75f',
    messagingSenderId: '74657022222',
    projectId: 'lab-firebase-bb91b',
    storageBucket: 'lab-firebase-bb91b.firebasestorage.app',
    iosBundleId: 'com.example.labFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2JKZkFCgxuJFd8GgPphPd2s83FIt9zgw',
    appId: '1:74657022222:web:d00f9d1c5c003ada8cd75f',
    messagingSenderId: '74657022222',
    projectId: 'lab-firebase-bb91b',
    authDomain: 'lab-firebase-bb91b.firebaseapp.com',
    storageBucket: 'lab-firebase-bb91b.firebasestorage.app',
    measurementId: 'G-XZZRR3LLK8',
  );
}
